### ISSUE TITLE
nixpkgs_package's nix_file attribute appears to be broken

### ISSUE THREAD

**Issue by grahamc** [tweag/rules_nixpkgs#14]
I'm looking to use nixpkgs_package along with a local nix file, contained within the same Git repository. This is to remove a large amount of Nix out of the WORKSPACE file and in to a properly named and syntax highlighted `.nix` file.

From what I've heard around town, this attribute doesn't actually work and is broken.

With 

```
nixpkgs_package(
  name = "...-toolchain",
  nix_file = ".circleci/tools.nix",
  attribute_path = "toolchain",
```

I get

```
ERROR: /home/grahamc/projects/.../BUILD:15:1: no such package '@...-toolchain//': Not a regular file: /home/grahamc/projects/.../external/.circleci/tools.nix and referenced by '//:...toolchain-impl'
```

@Fuuzetsu wonders if this is at fault:

```
if ctx.attr.nix_file and ctx.attr.nix_file_content:
    fail("Specify one of 'nix_file' or 'nix_file_content', but not both.")
  elif ctx.attr.nix_file:
    ctx.symlink(ctx.attr.nix_file, "default.nix")
  elif ctx.attr.nix_file_content:
expr_args = ["-E", ctx.attr.nix_file_content]
```

> Not too sure why we're doing this symlink thing, maybe that's a problem

**Comment by mboes** [comment]
I think the problem you're seeing is due to your label being wrong. In a WORKSPACE file, you should refer to local files by their absolute label, since in the WORKSPACE file you are not in the context of any particular package, so can't use relative names (see https://docs.bazel.build/versions/master/build-ref.html#labels).

That said, there *was* a problem with `nix_file` (now fixed in master). Some Skylark variable was not initialized in that code path (static analysis would have caught this).
