### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by jheaff1** [tweag/rules_nixpkgs#154]
Hi,

I would like to use rules_nixpkgs in an airgapped environment. May I ask what is the recommended way, if at all possible, to utilise rules_nixpkgs on a machine with no internet access?

Many thanks

**Comment by aherrmann** [comment]
The only component in `rules_nixpkgs` that fetches from the internet itself is `nixpkgs_git_repository`. You use `nixpkgs_local_repository` instead, like [here for example](https://github.com/tweag/rules_haskell/blob/c43b61b8ddad7a3f2064b3dab1f2fca9ca342bde/WORKSPACE#L156-L159) to point `rules_nixpkgs` to a `.nix` file that [fetches nixpkgs through Nix](https://github.com/tweag/rules_haskell/blob/master/nixpkgs/default.nix).

Apart from that `rules_nixpkgs` only calls out to `nix-build`. So, the remaining question is how to use Nix in an airgapped environment.
One option would be to use [`nix copy`](https://nixos.wiki/wiki/Nix_command/copy) to ship the required Nix derivations to the airgapped system on some medium, e.g. an external disk.
Alternatively, there was a related discussed on the NixOS discord [here](https://discourse.nixos.org/t/using-nixos-in-an-isolated-environment/3369), where a user only had low bandwidth internet access for a prolonged period of time. IIUC their solution was to provide a local copy of the nixpkgs binary cache.

For this use-case you will need to know which Nix expressions the project depends on. Unfortunately, Bazel has no equivalent of `bazel query` for repository rules. But, you can maintain a dedicated attribute set from which all `rules_nixpkgs` rules pick their inputs. So that e.g. `nix-build -A bazel ./bazel.nix` builds all required Nix dependencies of the project.

The following may be useful to know for debugging. `rules_nixpkgs` produces GC roots when building Nix packages. Assuming that all instances of `nixpkgs_package` are built, e.g. after `bazel sync`, you could use the following command to get a list of all these GC roots:
```
$ ls -1d $(bazel info output_base)/external/*/bazel-support/nix-out-link
```
Please note that this relies on implementation details of rules_nixpkgs. So, I would only recommend to use this for debugging purposes.

**Comment by jheaff1** [comment]
@aherrmann Thank you very much for prompt detailed response!
