### ISSUE TITLE
How to use opencv package in some python's binary?

### ISSUE THREAD

**Issue by bhavitsharma** [tweag/rules_nixpkgs#172]
I am trying to bring opencv package from the nix repository to use in some python application. However, running the binary fails because the binary is not able to find the required opencv library.
Executing the binary `bazel run :test_binary` gives `ImportError: libz.so.1: cannot open shared object file: No such file or directory`. This is on NixOS.

Here's my `WORKSPACE`

```BUILD
load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_package")
nixpkgs_package(
    name = "opencv",
    attribute_path = "opencv",
    repository = "@nixpkgs",
)
nixpkgs_package(
    name = "zlib",
    attribute_path = "zlib",
    repository = "@nixpkgs",
)

load("@rules_python//python:pip.bzl", "pip_install")
pip_install(
    requirements = "//:requirements.txt",
)
nixpkgs_python_configure(repository = "@nixpkgs")
```

and my build file being
```
py_binary(
	name = "test_binary",
	srcs = [ "hello.py"],
	main = "hello.py",
	data = [
		"@opencv//:lib", 
		"@opencv//:bin", 
		"@opencv//:include", 
		"@zlib//:lib",
		"@zlib//:include",
		"@zlib//:bin"
	],
	deps = [
		requirement("opencv-python"),
		requirement("numpy"),
	]
)
```

**Comment by bhavitsharma** [comment]
anyone familiar with how to bring nix's system packages with bazel?

**Comment by AlexeiDrake** [comment]
Hey @bhavitsharma. Thank you for your question.

Instead of using Pip, I recommend you use Nix to manage your dependencies, as you suggested. A Nix expression that adds OpenCV and Numpy to Python is as follows:

`python39.withPackages(ps: with ps; [ numpy opencv4 ])`
Of course you are free to change the Python version as needed.

`nixpkgs_python_configure` has a parameter allowing you to specify the Python package to use:

```
nixpkgs_python_configure(
    repository = "@nixpkgs",
    python3_attribute_path = "python39.withPackages(ps: with ps; [ numpy opencv4 ])"
)
```

I'll add an example to the repository to help others with this question.

To explain the problem you experienced with Pip. It is implemented as a repository rule, which means that it is not sandboxed and does not have access to toolchains like the one defined by `nixpkgs_python_configure`.

As such, it may pick a Python interpreter from the environment and install pip dependencies outside the sandbox.
If that setup picks up the wrong Python interpreter, then the installation will most likely be incompatible with the Nix provided one.

The pip-install part can be found here and surrounding files: https://github.com/bazelbuild/rules_python/blob/main/python/pip_install/pip_repository.bzl

**Comment by bhavitsharma** [comment]
@AlexeiDrake, saw your PR. Thank you so much, it looks great! The `nixpkgs_python_configure` seems to be some global rule which will be inherited by every python binary. Is it possible to use some packages for some binaries and other packages for other binaries? and is the workaround for it going to use multiple `WORKSPACES`?

**Comment by bhavitsharma** [comment]
Thanks, btw, for the sake of completeness, I am now building a docker image with all the system level packages and dependencies (evaluating the base image with `nixpkgs_package`). I think it's better because it's more flexible ( I can even use it for our nodejs applications) and all of our services run as a container only. 

I can contribute to your PR too :)

**Comment by AlexeiDrake** [comment]
The `nixpkgs_python_configure` is called in the WORKSPACE and will set up a Nix-based Python toolchain for all the Python rules in that workspace.

Going with one global toolchain that has all the packages is the simplest solution. The downside is of course that it's not fine grained and not incremental. Changing one external Python package will invalidate all Python targets, not just those that depend on the changed package.

A better solution would be to be able to pull in individual Python packages via `nixpkgs_package`. Unfortunately, rules_nixpkgs doesn't currently have support for this.
