### ISSUE TITLE
Regression: short form repository labels don't work anymore

### ISSUE THREAD

**Issue by mboes** [tweag/rules_nixpkgs#41]
It used to be possible to write this:

```python
nixpkgs_package(
  name = "foo",
  repository = "@nixpkgs",
)
```

This is a lot shorter than `repositories = {"nixpkgs": "@nixpkgs//:default.nix"}`. The reason this worked before is that we had a symlink that had the same name as the repository, pointing to `default.nix`, since `@foo` is actually syntactic sugar for `@foo//:foo` in Bazel.

It would be nice to have this shorthand available again. Incidentally, I think we should not deprecate `repository`, even though `repositories` now exists.

**Comment by Profpatsch** [comment]
I don’t understand where the symlink was before. IIRC I didn’t remove any symlinks (perhaps implicitely?).

Since `@foo` points to `@foo//:foo`, the repository needs a `BUILD` file with a `foo` target, right? Or alternatively export a `foo` file from its default package.

We only control the target repository if it was fetched via `nixpkgs_git_repository`, but `download_and_extract` only adds an empty `BUILD` file.

**Comment by regnat** [comment]
@Profpatsch The symlink wasn't needed because of the `dirname` hack removed by #34

**Comment by Profpatsch** [comment]
Yeah, that’s what I suspected. But then I don’t see how it defaulted to the target anyway. `@foo//:foo` is not `@foo//:nixpkgs.nix` after all.
